/**
 * Seed script for deadline_types table.
 *
 * Run with: npx tsx src/lib/db/seed-deadline-types.ts
 *
 * This populates the system catalog of Italian workplace safety deadlines
 * per D.Lgs. 81/08 and subsequent amendments (Legge 215/2021, DM 02/09/2021, etc.).
 */

import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { deadlineTypes, type NewDeadlineType } from './schema';

async function seed() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/safetrack',
  });
  const db = drizzle(pool);

  const seedData: NewDeadlineType[] = [
    // ─── FORMAZIONE ─────────────────────────────────────────────────────

    {
      name: 'Formazione Generale Lavoratori',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.1, lett. a) — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 0, // one-time, no renewal
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '4.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. c)',
      isSystem: true,
      sortOrder: 10,
    },
    {
      name: 'Formazione Specifica Lavoratori — Rischio Basso',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.1, lett. b) — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso'],
      durationHours: '4.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. c)',
      isSystem: true,
      sortOrder: 20,
    },
    {
      name: 'Formazione Specifica Lavoratori — Rischio Medio',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.1, lett. b) — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['medio'],
      durationHours: '8.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. c)',
      isSystem: true,
      sortOrder: 21,
    },
    {
      name: 'Formazione Specifica Lavoratori — Rischio Alto',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.1, lett. b) — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['alto'],
      durationHours: '12.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. c)',
      isSystem: true,
      sortOrder: 22,
    },
    {
      name: 'Aggiornamento Formazione Lavoratori',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.6 — Accordo Stato-Regioni 21/12/2011, punto 9',
      defaultPeriodicityMonths: 60,
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '6.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. c)',
      isSystem: true,
      sortOrder: 25,
    },
    {
      name: 'Formazione Preposti',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.7 — Legge 215/2021 (aggiornamento biennale)',
      defaultPeriodicityMonths: 24,
      appliesToAll: false,
      appliesToRoles: ['preposto'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '8.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. c)',
      isSystem: true,
      sortOrder: 30,
    },
    {
      name: 'Aggiornamento Preposti',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.7 — Legge 215/2021 (biennale obbligatorio)',
      defaultPeriodicityMonths: 24,
      appliesToAll: false,
      appliesToRoles: ['preposto'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '6.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 31,
    },
    {
      name: 'Formazione Dirigenti',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.7 — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['dirigente'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '16.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 40,
    },
    {
      name: 'Aggiornamento Dirigenti',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.7 — Accordo Stato-Regioni 21/12/2011, punto 9',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['dirigente'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '6.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 41,
    },
    {
      name: 'Formazione RLS (Rappresentante Lavoratori Sicurezza)',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.10-11 — min 32 ore iniziali',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['rls'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '32.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 50,
    },
    {
      name: 'Aggiornamento RLS (aziende >15 dipendenti)',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.11 — 8 ore/anno per >50 dip., 4 ore/anno per 15-50 dip.',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['rls'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '8.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 51,
    },
    {
      name: 'Formazione Addetti Primo Soccorso — Gruppo A',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 388/2003',
      defaultPeriodicityMonths: 36,
      appliesToAll: false,
      appliesToRoles: ['addetto_primo_soccorso'],
      riskLevels: ['alto'],
      durationHours: '16.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 60,
    },
    {
      name: 'Formazione Addetti Primo Soccorso — Gruppo B/C',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 388/2003',
      defaultPeriodicityMonths: 36,
      appliesToAll: false,
      appliesToRoles: ['addetto_primo_soccorso'],
      riskLevels: ['basso', 'medio'],
      durationHours: '12.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 61,
    },
    {
      name: 'Aggiornamento Addetti Primo Soccorso',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 388/2003, art. 3, c.5',
      defaultPeriodicityMonths: 36,
      appliesToAll: false,
      appliesToRoles: ['addetto_primo_soccorso'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '6.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 62,
    },
    {
      name: 'Formazione Addetti Antincendio — Livello 1',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 02/09/2021 (ex rischio basso)',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['addetto_antincendio'],
      riskLevels: ['basso'],
      durationHours: '4.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 70,
    },
    {
      name: 'Formazione Addetti Antincendio — Livello 2',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 02/09/2021 (ex rischio medio)',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['addetto_antincendio'],
      riskLevels: ['medio'],
      durationHours: '8.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 71,
    },
    {
      name: 'Formazione Addetti Antincendio — Livello 3',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 02/09/2021 (ex rischio alto)',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['addetto_antincendio'],
      riskLevels: ['alto'],
      durationHours: '16.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 72,
    },
    {
      name: 'Aggiornamento Addetti Antincendio',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 37, c.9 — DM 02/09/2021, art. 5',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['addetto_antincendio'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '5.0',
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 73,
    },
    {
      name: 'Formazione Lavori in Quota / DPI III Categoria',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 77, c.5 — Accordo Stato-Regioni 22/02/2012',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['operaio', 'preposto'],
      riskLevels: ['medio', 'alto'],
      durationHours: '8.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 80,
    },
    {
      name: 'Formazione Spazi Confinati',
      category: 'formazione',
      legalReference: 'DPR 177/2011 art. 2 — D.Lgs. 81/08 art. 66',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['operaio'],
      riskLevels: ['alto'],
      durationHours: '8.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 85,
    },
    {
      name: 'Abilitazione Carrelli Elevatori (Muletti)',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 73, c.5 — Accordo Stato-Regioni 22/02/2012, All. VI',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['operaio', 'carrellista'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '12.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 90,
    },
    {
      name: 'Abilitazione PLE — Piattaforme di Lavoro Elevabili',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 73, c.5 — Accordo Stato-Regioni 22/02/2012, All. III',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['operaio'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '10.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 91,
    },
    {
      name: 'Abilitazione Gru a Torre / Gru Mobile / Gru Autocarro',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 73, c.5 — Accordo Stato-Regioni 22/02/2012, All. IV-IX',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['operaio', 'gruista'],
      riskLevels: ['medio', 'alto'],
      durationHours: '14.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 92,
    },
    {
      name: 'Abilitazione Escavatori / Pale / Terne',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 73, c.5 — Accordo Stato-Regioni 22/02/2012, All. X',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['operaio'],
      riskLevels: ['medio', 'alto'],
      durationHours: '16.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 93,
    },
    {
      name: 'Abilitazione PES/PAV/PEI — Rischio Elettrico',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 82 — CEI 11-27',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['elettricista', 'manutentore'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: '16.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 95,
    },
    {
      name: 'Formazione RSPP Datore di Lavoro — Rischio Basso',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 34 — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['datore_lavoro'],
      riskLevels: ['basso'],
      durationHours: '16.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 100,
    },
    {
      name: 'Formazione RSPP Datore di Lavoro — Rischio Medio',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 34 — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['datore_lavoro'],
      riskLevels: ['medio'],
      durationHours: '32.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 101,
    },
    {
      name: 'Formazione RSPP Datore di Lavoro — Rischio Alto',
      category: 'formazione',
      legalReference: 'D.Lgs. 81/08 art. 34 — Accordo Stato-Regioni 21/12/2011',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: ['datore_lavoro'],
      riskLevels: ['alto'],
      durationHours: '48.0',
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 102,
    },

    // ─── SORVEGLIANZA SANITARIA ─────────────────────────────────────────

    {
      name: 'Visita Medica Preventiva (assunzione)',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 41, c.2, lett. a)',
      defaultPeriodicityMonths: 0, // one-time at hiring
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. d)',
      isSystem: true,
      sortOrder: 200,
    },
    {
      name: 'Visita Medica Periodica',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 41, c.2, lett. b) — di norma annuale, salvo diversa indicazione del MC',
      defaultPeriodicityMonths: 12,
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 210,
    },
    {
      name: 'Visita Medica su Richiesta del Lavoratore',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 41, c.2, lett. c)',
      defaultPeriodicityMonths: 0, // on demand
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: null,
      isSystem: true,
      sortOrder: 220,
    },
    {
      name: 'Visita Medica per Cambio Mansione',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 41, c.2, lett. d)',
      defaultPeriodicityMonths: 0, // event-triggered
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione penale per il datore di lavoro',
      isSystem: true,
      sortOrder: 225,
    },
    {
      name: 'Esame Audiometrico',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 196 — Titolo VIII, Capo II',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['operaio'],
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzioni per mancata sorveglianza sanitaria',
      isSystem: true,
      sortOrder: 230,
    },
    {
      name: 'Esame Spirometrico',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 229 — Titolo IX, Capo I',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['operaio'],
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzioni per mancata sorveglianza sanitaria',
      isSystem: true,
      sortOrder: 231,
    },
    {
      name: 'Drug Test (tossicodipendenza)',
      category: 'sorveglianza_sanitaria',
      legalReference: 'Provvedimento CU 30/10/2007 — DPR 309/90',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['carrellista', 'gruista', 'autista'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sospensione immediata dalla mansione',
      isSystem: true,
      sortOrder: 235,
    },
    {
      name: 'Alcoltest',
      category: 'sorveglianza_sanitaria',
      legalReference: 'D.Lgs. 81/08 art. 41, c.4 — Intesa CU 16/03/2006',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['carrellista', 'gruista', 'autista'],
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sospensione immediata dalla mansione',
      isSystem: true,
      sortOrder: 236,
    },

    // ─── DOCUMENTI AZIENDALI ────────────────────────────────────────────

    {
      name: 'DVR — Documento di Valutazione dei Rischi',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 17, c.1, lett. a) — art. 28-29',
      defaultPeriodicityMonths: 0, // update on changes, no fixed period
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44 (art. 55 c.1 lett. a)',
      isSystem: true,
      sortOrder: 300,
    },
    {
      name: 'DUVRI — Documento Unico Valutazione Rischi Interferenziali',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 26, c.3',
      defaultPeriodicityMonths: 0, // per contract
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23 (art. 55 c.5 lett. a)',
      isSystem: true,
      sortOrder: 310,
    },
    {
      name: 'Piano di Emergenza ed Evacuazione',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 43-46 — DM 02/09/2021',
      defaultPeriodicityMonths: 0, // update on changes
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 320,
    },
    {
      name: 'Prova di Evacuazione',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 43 — DM 02/09/2021, art. 4, c.2',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Ammenda e sanzioni amministrative',
      isSystem: true,
      sortOrder: 325,
    },
    {
      name: 'Registro Antincendio (controlli e manutenzioni)',
      category: 'documenti_aziendali',
      legalReference: 'DM 01/09/2021 (GSA) — obbligatorio dal 25/09/2022, Allegato I',
      defaultPeriodicityMonths: 6, // verifiche semestrali minime
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzioni art. 46 D.Lgs. 81/08 — ammenda e prescrizioni ASL',
      isSystem: true,
      sortOrder: 330,
    },
    {
      name: 'Nomina RSPP',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 17, c.1, lett. b)',
      defaultPeriodicityMonths: 0, // no expiry, update on change
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 340,
    },
    {
      name: 'Nomina Medico Competente',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 18, c.1, lett. a)',
      defaultPeriodicityMonths: 0, // no expiry
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.843,02 a €7.371,02',
      isSystem: true,
      sortOrder: 345,
    },
    {
      name: 'Patente a Crediti Cantieri',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 27 — obbligo dal 01/10/2024',
      defaultPeriodicityMonths: 0, // maintained continuously
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['alto'],
      durationHours: null,
      sanctionInfo: 'Sospensione attivita di cantiere — sanzione amministrativa da €6.000 a €12.000',
      isSystem: true,
      sortOrder: 350,
    },
    {
      name: 'POS — Piano Operativo di Sicurezza',
      category: 'documenti_aziendali',
      legalReference: 'D.Lgs. 81/08 art. 89, c.1, lett. h) — Allegato XV',
      defaultPeriodicityMonths: 0, // per cantiere
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 355,
    },

    // ─── VERIFICHE IMPIANTI ─────────────────────────────────────────────

    {
      name: 'Verifica Impianto Messa a Terra — Cat. I e III (cantieri/locali medici)',
      category: 'verifiche_impianti',
      legalReference: 'DPR 462/2001 art. 4 — verifica biennale',
      defaultPeriodicityMonths: 24,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione amministrativa da €516 a €2.582 (art. 9 DPR 462/2001)',
      isSystem: true,
      sortOrder: 400,
    },
    {
      name: 'Verifica Impianto Messa a Terra — Cat. II (altri ambienti)',
      category: 'verifiche_impianti',
      legalReference: 'DPR 462/2001 art. 4 — verifica quinquennale',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione amministrativa da €516 a €2.582',
      isSystem: true,
      sortOrder: 401,
    },
    {
      name: 'Verifica Scariche Atmosferiche',
      category: 'verifiche_impianti',
      legalReference: 'DPR 462/2001 art. 6 — biennale/quinquennale',
      defaultPeriodicityMonths: 24,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione amministrativa da €516 a €2.582',
      isSystem: true,
      sortOrder: 405,
    },
    {
      name: 'Verifica Ascensori e Montacarichi',
      category: 'verifiche_impianti',
      legalReference: 'DPR 162/1999 art. 13 — verifica biennale',
      defaultPeriodicityMonths: 24,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione amministrativa e sequestro dell\'impianto',
      isSystem: true,
      sortOrder: 410,
    },
    {
      name: 'Verifica Apparecchi a Pressione',
      category: 'verifiche_impianti',
      legalReference: 'D.Lgs. 81/08 art. 71, c.11 — DM 11/04/2011, All. VII',
      defaultPeriodicityMonths: 36, // varies: 2-5 years depending on category
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 420,
    },
    {
      name: 'CPI — Certificato Prevenzione Incendi',
      category: 'verifiche_impianti',
      legalReference: 'DPR 151/2011 — rinnovo quinquennale (Cat. B e C)',
      defaultPeriodicityMonths: 60,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione penale art. 20 D.Lgs. 139/2006 — arresto fino a 1 anno o ammenda',
      isSystem: true,
      sortOrder: 430,
    },
    {
      name: 'Verifica Attrezzature di Sollevamento (gru, carroponti, paranchi)',
      category: 'verifiche_impianti',
      legalReference: 'D.Lgs. 81/08 art. 71, c.11 — DM 11/04/2011, All. VII, Tabella',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 3 a 6 mesi o ammenda da €3.071,27 a €7.862,44',
      isSystem: true,
      sortOrder: 435,
    },

    // ─── DPI ────────────────────────────────────────────────────────────

    {
      name: 'Consegna DPI — Dispositivi di Protezione Individuale',
      category: 'dpi',
      legalReference: 'D.Lgs. 81/08 art. 77 — consegna all\'assunzione + sostituzione',
      defaultPeriodicityMonths: 0, // event-triggered (hiring + replacement)
      appliesToAll: true,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Arresto da 2 a 4 mesi o ammenda da €1.474,21 a €6.388,23',
      isSystem: true,
      sortOrder: 500,
    },
    {
      name: 'Verifica Stato DPI III Categoria (imbracature, DPI anticaduta)',
      category: 'dpi',
      legalReference: 'D.Lgs. 81/08 art. 77, c.4, lett. a) — manutenzione secondo fabbricante',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: ['operaio'],
      riskLevels: ['medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Responsabilita del datore in caso di infortunio',
      isSystem: true,
      sortOrder: 510,
    },

    // ─── ALTRO ──────────────────────────────────────────────────────────

    {
      name: 'RENTRI — Registro Elettronico Tracciabilita Rifiuti',
      category: 'altro',
      legalReference: 'DM 04/04/2023 n.59 — obbligo progressivo 2025-2026',
      defaultPeriodicityMonths: 0, // continuous obligation
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzioni amministrative da €2.600 a €15.500',
      isSystem: true,
      sortOrder: 600,
    },
    {
      name: 'Comunicazione Annuale Rifiuti — MUD',
      category: 'altro',
      legalReference: 'D.Lgs. 152/2006 art. 189 — entro 30 aprile di ogni anno',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione amministrativa da €2.600 a €15.500',
      isSystem: true,
      sortOrder: 610,
    },
    {
      name: 'Denuncia INAIL Nuovo Impianto / Messa a Terra',
      category: 'altro',
      legalReference: 'DPR 462/2001 art. 2 — entro 30 giorni dalla messa in esercizio',
      defaultPeriodicityMonths: 0, // one-time per impianto
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Sanzione amministrativa',
      isSystem: true,
      sortOrder: 620,
    },
    {
      name: 'Riunione Periodica Sicurezza (aziende >15 dipendenti)',
      category: 'altro',
      legalReference: 'D.Lgs. 81/08 art. 35 — almeno annuale',
      defaultPeriodicityMonths: 12,
      appliesToAll: false,
      appliesToRoles: null,
      riskLevels: ['basso', 'medio', 'alto'],
      durationHours: null,
      sanctionInfo: 'Ammenda da €2.457,02 a €4.914,03 (art. 55 c.5 lett. d)',
      isSystem: true,
      sortOrder: 630,
    },
  ];

  console.log(`Seeding ${seedData.length} deadline types...`);

  await db.insert(deadlineTypes).values(seedData);

  console.log(`Successfully seeded ${seedData.length} deadline types.`);
}

seed()
  .then(() => {
    console.log('Seed complete.');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Seed failed:', error);
    process.exit(1);
  });
